config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'users#profile'
  patch 'profile', to: 'users#update_avatar'
  get 'match', to: 'users#match'
  get 'match-me', to: 'users#match_me'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord    

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :interests

  def update_with_password(params, *options)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if params[:password].blank? || valid_password?(current_password)
      update_attributes(params, *options)
    else
      self.assign_attributes(params, *options)
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end

    clean_up_passwords
    result
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController

    def new
      super
    end

    def create
      params[:user][:interests] = params[:user][:interests].split(',');
        
        super
        
        params[:user][:interests].each do |interest|
          if Interest.exists?(:name => interest)
            resource.interests.push(Interest.find_by_name interest)
          else
            resource.interests.push(Interest.create(name: interest))
          end
        end
    end



    private

    def sign_up_params
      params.require(:user).permit(:name, :interests, :avatar, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :avatar, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def profile
		@user = current_user

		@interests = []

		@user.interests.each do |x|
			@interests.push(x.name)
		end
	end	

	def update_avatar
		@user = current_user
		
		if @user.update_attributes(user_params)
	      redirect_to profile_path :notice  => "Successfully updated ."
	    else
	      render :action => 'edit'
	    end

	end

	def edit
		@user = current_user

		@interests = []

		@user.interests.each do |interest|
			@interests.push(interest.name)
		end

		@interests = @interests.join(", ")
	end

	def update
		@user = current_user

		@user.interests.destroy_all

		@interests = []
		params[:user][:interests].split(',').each do |interest|
			if Interest.exists?(:name => interest)
				@user.interests.push(Interest.find_by_name interest)
			else
				@user.interests.push(Interest.create(name: interest))
			end
		end

		@user.name = params[:user][:name]

		@user.avatar = params[:user][:avatar]

		if @user.save
			redirect_to profile_path :notice  => "Successfully updated ."
		else
			render :action => 'edit'
		end
	end	

	def match
		@user = current_user
		@interests = current_user.interests

		@matched_users = []

		@interests.each do |interest|
			users = interest.users
			users.each do |u|
				@matched_users.push(u) if u.id != @user.id
			end
		end

		@matched_users = @matched_users.uniq { |u| u.id }
	end

	def match_me
		@user = current_user
		@interests = current_user.interests

		@matched_users = []

		@interests.each do |interest|
			users = interest.users
			users.each do |u|
				@matched_users.push(u) if u.id != @user.id
			end
		end



		@matched_users = @matched_users.uniq { |u| u.id }
		respond_to do |format|
	      format.js   {}
	      format.json { render json: @matched_users.sample}
	  	end
	end

	def user_params
	  params.require(:user).permit(:avatar, :name, :interests)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2 class="text-center">Edit <%= @user.email %></h2>

<%= form_for(@user, url: user_path, html: { method: :put }) do |f| %>

  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="jumbotron">
          <div class="field form-group">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, :class => 'form-control', :value => @user.name%>
          </div>

          <div class="field form-group">
            <%= f.label :avatar %><br />
            <%= f.file_field :avatar, :class => 'form-control', :value => @user.avatar.url%>
          </div>

          <div class="form-group">
            <%= f.label :interests %><br />
            <%= f.text_field :interests, :value => @interests, :class => 'form-control', 'data-role' => 'tagsinput' %>
          </div>

          <div class="form-group">
            <%= f.submit "Update", :class => 'btn btn-primary'%>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/match.html.erb
<h2 class="text-center"> You are matching with: <%= @matched_users.length %> User!</h2>

<button id="match-me" class="btn btn-primary center-block"> Discover your weekly match</button>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 well hidden">
			<h2 id="match-name" class="text-center">  </h2>
			<img id="match-avatar" src="">
		</div>
	</div>
</div>

<script>
	$('#match-me').click(function(){
		//console.log('click');
		var url = '/match-me'
		$.ajax({
		  dataType: "json",
		  url: url,
		  success: function(data){
		  	$('#match-name').text(data.name);
		  	$('#match-avatar').attr('src', data.avatar);
		  	$('.hidden').removeClass('hidden');
		  }
		});
	})
</script>
<!-- <table class="table table-condensed">
	<thead>
		<tr>
			<th>Name</th>
			<th>Interest</th>
		</tr>
	</thead>
	<tbody>
		<% @matched_users.each do |user| %>
			<tr>
				<td><%= user.name %></td>
				<td><%= user.interests[0].name %></td>
			</tr>
		<% end %>
	</tbody>
</table> -->

app/views/users/profile.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2> <%= @user.name %>'s Profile </h2>
            <%= image_tag @user.avatar.url %>
            <h2> <%= @interests%> </h2>
            <%= form_for @user, url: profile_path, html: { multipart: true } do |f| %>
                <%= f.file_field :avatar %>
                <%= f.submit "Update", :class => 'btn btn-primary'%>
            <% end %>

            <%= link_to "Edit", edit_user_path(current_user)  %>
        </div>
    </div>
</div>