config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'profile', to: 'users#profile'
  patch 'profile', to: 'users#update_avatar'
  get 'match', to: 'users#match'
  get 'match-me', to: 'users#match_me'
  devise_for :users, :controllers => { :registrations => "users/registrations"}
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Randomeet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  	<% if user_signed_in? %>
		<nav class="navbar navbar-default navbar-static-top" role="navigation">
		  <div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
		        <span class="sr-only"> Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      
		      <a class="navbar-brand text-right" href="/" style="padding: 0px">
		          <img alt="Brand" src="assets/randomeet.png" class="navbar-img" style="height: 50px; width: auto">
		      </a>
		    </div>
		    
		    <div class="collapse navbar-collapse" id="main-nav-collapse">

		    	<!-- Left Side Of Navbar -->
	            <ul class="nav navbar-nav">
	                <li><%= link_to "Home", root_path %></li>
	                <li><%= link_to "Match me", match_path %></li>
	            </ul>

		    	<ul class="nav navbar-nav navbar-right">
		        	<% if user_signed_in? %>
		        		<li><%= image_tag current_user.avatar.url, :class => "img-responsive img-circle"%></li>
	                    <li class="dropdown">
	                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
	                        	<%= current_user.name %> <span class="caret"></span>
	                        </a>

	                        <ul class="dropdown-menu" role="menu">
	                        	<li><%= link_to "Profile", profile_path %></li>
	                        	<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	                        </ul>
	                    </li>
		        	<% else %>
		          		<%= link_to "Log In", new_user_session_path, class: 'btn btn-primary', method: :get %>
		        	<% end %>
		    	</ul>
		    </div>
		  </div>
		</nav>
		<% end %>
		<!-- <div class="bg"> -->
			<div class="container">
		    	<%= yield %>
		    </div>
	    <!-- </div> -->
	
		<!-- <div class="container">
			<h1 id="welcome-heading" class="text-center"> WELCOME TO RANDOMEET </h1>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="row">
						<div class="col-md-6 text-center">
							<%= link_to "About", about_path, :class => "btn btn-primary" %></li>
						</div>
						<div class="col-md-6 text-center">
							<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success"%></li>
						</div>
					</div>
				</div>
			</div>
		</div> -->
		
		<!-- <div class="cover">
		  <div class="clearfix"></div>
		   <nav>
		    <ul>
		    <li><a href="#portfolio">SHOP</a></li>
		    <li><a href="#about">ABOUT</a></li>
		    <li><a href="#contact">PRESS</a></li>
		    </ul>
		  </nav> 
		</div>-->
  </body>
</html>